window.SENTINEL_DATA = {

  TYPES: {
    malware:  { label: 'Malware',  color: '#ff3355', cls: 't-malware',  severity: 'CRITICAL' },
    ddos:     { label: 'DDoS',     color: '#ffaa00', cls: 't-ddos',     severity: 'HIGH'     },
    phishing: { label: 'Phishing', color: '#aa44ff', cls: 't-phishing', severity: 'HIGH'     },
    recon:    { label: 'Recon',    color: '#00d4ff', cls: 't-recon',    severity: 'MEDIUM'   },
    c2:       { label: 'C2',       color: '#00ff88', cls: 't-c2',       severity: 'CRITICAL' },
    exploit:  { label: 'Exploit',  color: '#ff8844', cls: 't-exploit',  severity: 'CRITICAL' },
  },

  // ISO 3166-1 alpha-2 → display name (must match GEO keys)
  ISO_TO_COUNTRY: {
    'CN': 'China',          'US': 'United States', 'RU': 'Russia',
    'BR': 'Brazil',         'IN': 'India',         'DE': 'Germany',
    'NL': 'Netherlands',    'FR': 'France',        'GB': 'United Kingdom',
    'KR': 'South Korea',    'JP': 'Japan',         'UA': 'Ukraine',
    'VN': 'Vietnam',        'IR': 'Iran',          'TR': 'Turkey',
    'ID': 'Indonesia',      'MX': 'Mexico',        'PK': 'Pakistan',
    'NG': 'Nigeria',        'ZA': 'South Africa',  'AU': 'Australia',
    'CA': 'Canada',         'AR': 'Argentina',     'EG': 'Egypt',
    'RO': 'Romania',        'BG': 'Bulgaria',      'PL': 'Poland',
    'KP': 'North Korea',    'BY': 'Belarus',       'IL': 'Israel',
    'HK': 'Hong Kong',      'SG': 'Singapore',     'TW': 'Taiwan',
    'TH': 'Thailand',       'MY': 'Malaysia',      'PH': 'Philippines',
    'CZ': 'Czech Republic', 'HU': 'Hungary',       'RS': 'Serbia',
    'MD': 'Moldova',        'KZ': 'Kazakhstan',    'LT': 'Lithuania',
    'LV': 'Latvia',         'EE': 'Estonia',       'FI': 'Finland',
    'SE': 'Sweden',         'NO': 'Norway',        'DK': 'Denmark',
    'ES': 'Spain',          'PT': 'Portugal',      'IT': 'Italy',
    'GR': 'Greece',         'CH': 'Switzerland',   'AT': 'Austria',
    'BE': 'Belgium',        'CL': 'Chile',         'CO': 'Colombia',
    'PE': 'Peru',           'VE': 'Venezuela',     'SA': 'Saudi Arabia',
    'AE': 'UAE',            'MA': 'Morocco',       'DZ': 'Algeria',
    'BD': 'Bangladesh',     'LK': 'Sri Lanka',     'MM': 'Myanmar',
    'NP': 'Nepal',          'SK': 'Slovakia',      'HR': 'Croatia',
    'AZ': 'Azerbaijan',     'GE': 'Georgia',       'AM': 'Armenia',
    'UZ': 'Uzbekistan',
  },

  // [longitude, latitude] — major city per country
  GEO: {
    'China':          [ 116.4,  39.9],
    'United States':  [ -77.0,  38.9],
    'Russia':         [  37.6,  55.8],
    'Brazil':         [ -47.9, -15.8],
    'India':          [  77.2,  28.6],
    'Germany':        [  13.4,  52.5],
    'Netherlands':    [   4.9,  52.4],
    'France':         [   2.3,  48.9],
    'United Kingdom': [  -0.1,  51.5],
    'South Korea':    [ 126.9,  37.6],
    'Japan':          [ 139.7,  35.7],
    'Ukraine':        [  30.5,  50.5],
    'Vietnam':        [ 105.8,  21.0],
    'Iran':           [  51.4,  35.7],
    'Turkey':         [  32.9,  39.9],
    'Indonesia':      [ 106.8,  -6.2],
    'Mexico':         [ -99.1,  19.4],
    'Pakistan':       [  73.1,  33.7],
    'Nigeria':        [   7.5,   9.1],
    'South Africa':   [  28.0, -26.2],
    'Australia':      [ 149.1, -35.3],
    'Canada':         [ -75.7,  45.4],
    'Argentina':      [ -58.4, -34.6],
    'Egypt':          [  31.2,  30.1],
    'Romania':        [  26.1,  44.4],
    'Bulgaria':       [  23.3,  42.7],
    'Poland':         [  21.0,  52.2],
    'North Korea':    [ 125.7,  39.0],
    'Belarus':        [  27.6,  53.9],
    'Israel':         [  35.2,  31.8],
    'Hong Kong':      [ 114.2,  22.3],
    'Singapore':      [ 103.8,   1.3],
    'Taiwan':         [ 121.6,  25.0],
    'Thailand':       [ 100.5,  13.8],
    'Malaysia':       [ 101.7,   3.1],
    'Philippines':    [ 121.0,  14.6],
    'Czech Republic': [  14.5,  50.1],
    'Hungary':        [  19.0,  47.5],
    'Serbia':         [  20.5,  44.8],
    'Moldova':        [  28.8,  47.0],
    'Kazakhstan':     [  71.4,  51.2],
    'Lithuania':      [  25.3,  54.7],
    'Latvia':         [  24.1,  56.9],
    'Estonia':        [  24.7,  59.4],
    'Finland':        [  25.0,  60.2],
    'Sweden':         [  18.1,  59.3],
    'Norway':         [  10.8,  59.9],
    'Denmark':        [  12.6,  55.7],
    'Spain':          [  -3.7,  40.4],
    'Portugal':       [  -9.1,  38.7],
    'Italy':          [  12.5,  41.9],
    'Greece':         [  23.7,  37.9],
    'Switzerland':    [   8.5,  47.4],
    'Austria':        [  16.4,  48.2],
    'Belgium':        [   4.4,  50.8],
    'Chile':          [ -70.7, -33.5],
    'Colombia':       [ -74.1,   4.7],
    'Peru':           [ -77.0, -12.0],
    'Venezuela':      [ -66.9,  10.5],
    'Saudi Arabia':   [  46.7,  24.7],
    'UAE':            [  55.3,  25.2],
    'Morocco':        [  -5.8,  34.0],
    'Algeria':        [   3.1,  36.8],
    'Bangladesh':     [  90.4,  23.7],
    'Sri Lanka':      [  79.9,   6.9],
    'Myanmar':        [  96.2,  16.9],
    'Nepal':          [  85.3,  27.7],
    'Slovakia':       [  17.1,  48.1],
    'Croatia':        [  16.0,  45.8],
    'Azerbaijan':     [  49.9,  40.4],
    'Georgia':        [  44.8,  41.7],
    'Armenia':        [  44.5,  40.2],
    'Uzbekistan':     [  69.3,  41.3],
  },

  FLAGS: {
    'China': '🇨🇳',          'United States': '🇺🇸', 'Russia': '🇷🇺',
    'Brazil': '🇧🇷',         'India': '🇮🇳',          'Germany': '🇩🇪',
    'Netherlands': '🇳🇱',    'France': '🇫🇷',         'United Kingdom': '🇬🇧',
    'South Korea': '🇰🇷',    'Japan': '🇯🇵',           'Ukraine': '🇺🇦',
    'Vietnam': '🇻🇳',         'Iran': '🇮🇷',            'Turkey': '🇹🇷',
    'Indonesia': '🇮🇩',       'Mexico': '🇲🇽',          'Pakistan': '🇵🇰',
    'Nigeria': '🇳🇬',          'South Africa': '🇿🇦',  'Australia': '🇦🇺',
    'Canada': '🇨🇦',           'Argentina': '🇦🇷',      'Egypt': '🇪🇬',
    'Romania': '🇷🇴',          'Bulgaria': '🇧🇬',       'Poland': '🇵🇱',
    'North Korea': '🇰🇵',     'Belarus': '🇧🇾',         'Israel': '🇮🇱',
    'Hong Kong': '🇭🇰',        'Singapore': '🇸🇬',      'Taiwan': '🇹🇼',
    'Thailand': '🇹🇭',         'Malaysia': '🇲🇾',        'Philippines': '🇵🇭',
    'Czech Republic': '🇨🇿',  'Hungary': '🇭🇺',         'Serbia': '🇷🇸',
    'Moldova': '🇲🇩',          'Kazakhstan': '🇰🇿',     'Lithuania': '🇱🇹',
    'Latvia': '🇱🇻',            'Estonia': '🇪🇪',         'Finland': '🇫🇮',
    'Sweden': '🇸🇪',            'Norway': '🇳🇴',          'Denmark': '🇩🇰',
    'Spain': '🇪🇸',              'Portugal': '🇵🇹',        'Italy': '🇮🇹',
    'Greece': '🇬🇷',             'Switzerland': '🇨🇭',    'Austria': '🇦🇹',
    'Belgium': '🇧🇪',            'Chile': '🇨🇱',           'Colombia': '🇨🇴',
    'Peru': '🇵🇪',               'Venezuela': '🇻🇪',       'Saudi Arabia': '🇸🇦',
    'UAE': '🇦🇪',                'Morocco': '🇲🇦',          'Algeria': '🇩🇿',
    'Bangladesh': '🇧🇩',        'Sri Lanka': '🇱🇰',       'Myanmar': '🇲🇲',
    'Nepal': '🇳🇵',              'Slovakia': '🇸🇰',         'Croatia': '🇭🇷',
    'Azerbaijan': '🇦🇿',        'Georgia': '🇬🇪',           'Armenia': '🇦🇲',
    'Uzbekistan': '🇺🇿',
  },

  // Fallback simulation scenarios (used when all live feeds fail)
  SCENARIOS: [
    { src: 'China',        tgt: 'United States',  type: 'malware'  },
    { src: 'Russia',       tgt: 'Germany',        type: 'phishing' },
    { src: 'China',        tgt: 'United Kingdom', type: 'malware'  },
    { src: 'India',        tgt: 'United States',  type: 'recon'    },
    { src: 'Brazil',       tgt: 'United States',  type: 'ddos'     },
    { src: 'Vietnam',      tgt: 'Japan',          type: 'malware'  },
    { src: 'Iran',         tgt: 'United States',  type: 'c2'       },
    { src: 'Turkey',       tgt: 'Germany',        type: 'ddos'     },
    { src: 'Nigeria',      tgt: 'United Kingdom', type: 'phishing' },
    { src: 'Russia',       tgt: 'Ukraine',        type: 'exploit'  },
    { src: 'South Korea',  tgt: 'Japan',          type: 'recon'    },
    { src: 'Indonesia',    tgt: 'Australia',      type: 'ddos'     },
    { src: 'Pakistan',     tgt: 'India',          type: 'malware'  },
    { src: 'China',        tgt: 'Australia',      type: 'c2'       },
    { src: 'Mexico',       tgt: 'United States',  type: 'phishing' },
    { src: 'South Africa', tgt: 'France',         type: 'recon'    },
    { src: 'North Korea',  tgt: 'South Korea',    type: 'exploit'  },
    { src: 'Romania',      tgt: 'United States',  type: 'malware'  },
    { src: 'Belarus',      tgt: 'United Kingdom', type: 'c2'       },
    { src: 'Iran',         tgt: 'Israel',         type: 'exploit'  },
    { src: 'Bulgaria',     tgt: 'Germany',        type: 'phishing' },
    { src: 'Russia',       tgt: 'United States',  type: 'exploit'  },
    { src: 'China',        tgt: 'Canada',         type: 'recon'    },
    { src: 'Vietnam',      tgt: 'Australia',      type: 'malware'  },
    { src: 'Indonesia',    tgt: 'Japan',          type: 'ddos'     },
    { src: 'Nigeria',      tgt: 'Netherlands',    type: 'phishing' },
    { src: 'Egypt',        tgt: 'France',         type: 'recon'    },
    { src: 'Argentina',    tgt: 'Brazil',         type: 'malware'  },
    { src: 'Poland',       tgt: 'Germany',        type: 'ddos'     },
    { src: 'North Korea',  tgt: 'United States',  type: 'c2'       },
    { src: 'Hong Kong',    tgt: 'United States',  type: 'malware'  },
    { src: 'Singapore',    tgt: 'Australia',      type: 'recon'    },
    { src: 'Lithuania',    tgt: 'Germany',        type: 'c2'       },
    { src: 'Czech Republic', tgt: 'United States', type: 'malware' },
    { src: 'Serbia',       tgt: 'United Kingdom', type: 'phishing' },
    { src: 'Kazakhstan',   tgt: 'Germany',        type: 'c2'       },
    { src: 'Moldova',      tgt: 'France',         type: 'malware'  },
    { src: 'Hungary',      tgt: 'United States',  type: 'phishing' },
  ],
};
