window.AZIMUTH_DATA = {

  TYPES: {
    malware:  { label: 'Malware',  color: '#ff3355', cls: 't-malware',  severity: 'CRITICAL' },
    ddos:     { label: 'DDoS',     color: '#ffaa00', cls: 't-ddos',     severity: 'HIGH'     },
    phishing: { label: 'Phishing', color: '#aa44ff', cls: 't-phishing', severity: 'HIGH'     },
    recon:    { label: 'Recon',    color: '#00d4ff', cls: 't-recon',    severity: 'MEDIUM'   },
    c2:       { label: 'C2',       color: '#00ff88', cls: 't-c2',       severity: 'CRITICAL' },
    exploit:  { label: 'Exploit',  color: '#ff8844', cls: 't-exploit',  severity: 'CRITICAL' },
  },

  // ISO 3166-1 alpha-2 → display name (must match GEO keys)
  ISO_TO_COUNTRY: {
    'CN': 'China',          'US': 'United States', 'RU': 'Russia',
    'BR': 'Brazil',         'IN': 'India',         'DE': 'Germany',
    'NL': 'Netherlands',    'FR': 'France',        'GB': 'United Kingdom',
    'KR': 'South Korea',    'JP': 'Japan',         'UA': 'Ukraine',
    'VN': 'Vietnam',        'IR': 'Iran',          'TR': 'Turkey',
    'ID': 'Indonesia',      'MX': 'Mexico',        'PK': 'Pakistan',
    'NG': 'Nigeria',        'ZA': 'South Africa',  'AU': 'Australia',
    'CA': 'Canada',         'AR': 'Argentina',     'EG': 'Egypt',
    'RO': 'Romania',        'BG': 'Bulgaria',      'PL': 'Poland',
    'KP': 'North Korea',    'BY': 'Belarus',       'IL': 'Israel',
    'HK': 'Hong Kong',      'SG': 'Singapore',     'TW': 'Taiwan',
    'TH': 'Thailand',       'MY': 'Malaysia',      'PH': 'Philippines',
    'CZ': 'Czech Republic', 'HU': 'Hungary',       'RS': 'Serbia',
    'MD': 'Moldova',        'KZ': 'Kazakhstan',    'LT': 'Lithuania',
    'LV': 'Latvia',         'EE': 'Estonia',       'FI': 'Finland',
    'SE': 'Sweden',         'NO': 'Norway',        'DK': 'Denmark',
    'ES': 'Spain',          'PT': 'Portugal',      'IT': 'Italy',
    'GR': 'Greece',         'CH': 'Switzerland',   'AT': 'Austria',
    'BE': 'Belgium',        'CL': 'Chile',         'CO': 'Colombia',
    'PE': 'Peru',           'VE': 'Venezuela',     'SA': 'Saudi Arabia',
    'AE': 'UAE',            'MA': 'Morocco',       'DZ': 'Algeria',
    'BD': 'Bangladesh',     'LK': 'Sri Lanka',     'MM': 'Myanmar',
    'NP': 'Nepal',          'SK': 'Slovakia',      'HR': 'Croatia',
    'AZ': 'Azerbaijan',     'GE': 'Georgia',       'AM': 'Armenia',
    'UZ': 'Uzbekistan',
    // Africa
    'KE': 'Kenya',          'TZ': 'Tanzania',      'ET': 'Ethiopia',
    'GH': 'Ghana',          'CI': 'Ivory Coast',   'CM': 'Cameroon',
    'AO': 'Angola',         'MZ': 'Mozambique',    'ZW': 'Zimbabwe',
    'ZM': 'Zambia',         'UG': 'Uganda',        'RW': 'Rwanda',
    'SD': 'Sudan',          'CD': 'DR Congo',      'SN': 'Senegal',
    'LY': 'Libya',          'TN': 'Tunisia',       'SO': 'Somalia',
    'NA': 'Namibia',        'BW': 'Botswana',      'MG': 'Madagascar',
    'ML': 'Mali',           'MW': 'Malawi',        'BF': 'Burkina Faso',
    'NE': 'Niger',          'TG': 'Togo',          'BJ': 'Benin',
    'GN': 'Guinea',         'MU': 'Mauritius',
    // Middle East
    'IQ': 'Iraq',           'SY': 'Syria',         'JO': 'Jordan',
    'KW': 'Kuwait',         'QA': 'Qatar',         'BH': 'Bahrain',
    'OM': 'Oman',           'LB': 'Lebanon',       'YE': 'Yemen',
    'PS': 'Palestine',
    // Central & South Asia
    'AF': 'Afghanistan',    'KG': 'Kyrgyzstan',    'TJ': 'Tajikistan',
    'TM': 'Turkmenistan',
    // East & Southeast Asia
    'KH': 'Cambodia',       'LA': 'Laos',          'MN': 'Mongolia',
    // Europe
    'AL': 'Albania',        'BA': 'Bosnia',        'MK': 'North Macedonia',
    'ME': 'Montenegro',     'IS': 'Iceland',       'LU': 'Luxembourg',
    'MT': 'Malta',          'CY': 'Cyprus',        'IE': 'Ireland',
    'SI': 'Slovenia',
    // Americas
    'BO': 'Bolivia',        'EC': 'Ecuador',       'PY': 'Paraguay',
    'UY': 'Uruguay',        'CU': 'Cuba',          'DO': 'Dominican Republic',
    'HN': 'Honduras',       'GT': 'Guatemala',     'SV': 'El Salvador',
    'CR': 'Costa Rica',     'PA': 'Panama',        'NI': 'Nicaragua',
    'GY': 'Guyana',         'TT': 'Trinidad and Tobago', 'JM': 'Jamaica',
    'HT': 'Haiti',
    // Oceania
    'NZ': 'New Zealand',    'PG': 'Papua New Guinea', 'FJ': 'Fiji',
  },

  // [longitude, latitude] — major city per country
  GEO: {
    'China':          [ 116.4,  39.9],
    'United States':  [ -77.0,  38.9],
    'Russia':         [  37.6,  55.8],
    'Brazil':         [ -47.9, -15.8],
    'India':          [  77.2,  28.6],
    'Germany':        [  13.4,  52.5],
    'Netherlands':    [   4.9,  52.4],
    'France':         [   2.3,  48.9],
    'United Kingdom': [  -0.1,  51.5],
    'South Korea':    [ 126.9,  37.6],
    'Japan':          [ 139.7,  35.7],
    'Ukraine':        [  30.5,  50.5],
    'Vietnam':        [ 105.8,  21.0],
    'Iran':           [  51.4,  35.7],
    'Turkey':         [  32.9,  39.9],
    'Indonesia':      [ 106.8,  -6.2],
    'Mexico':         [ -99.1,  19.4],
    'Pakistan':       [  73.1,  33.7],
    'Nigeria':        [   7.5,   9.1],
    'South Africa':   [  28.0, -26.2],
    'Australia':      [ 149.1, -35.3],
    'Canada':         [ -75.7,  45.4],
    'Argentina':      [ -58.4, -34.6],
    'Egypt':          [  31.2,  30.1],
    'Romania':        [  26.1,  44.4],
    'Bulgaria':       [  23.3,  42.7],
    'Poland':         [  21.0,  52.2],
    'North Korea':    [ 125.7,  39.0],
    'Belarus':        [  27.6,  53.9],
    'Israel':         [  35.2,  31.8],
    'Hong Kong':      [ 114.2,  22.3],
    'Singapore':      [ 103.8,   1.3],
    'Taiwan':         [ 121.6,  25.0],
    'Thailand':       [ 100.5,  13.8],
    'Malaysia':       [ 101.7,   3.1],
    'Philippines':    [ 121.0,  14.6],
    'Czech Republic': [  14.5,  50.1],
    'Hungary':        [  19.0,  47.5],
    'Serbia':         [  20.5,  44.8],
    'Moldova':        [  28.8,  47.0],
    'Kazakhstan':     [  71.4,  51.2],
    'Lithuania':      [  25.3,  54.7],
    'Latvia':         [  24.1,  56.9],
    'Estonia':        [  24.7,  59.4],
    'Finland':        [  25.0,  60.2],
    'Sweden':         [  18.1,  59.3],
    'Norway':         [  10.8,  59.9],
    'Denmark':        [  12.6,  55.7],
    'Spain':          [  -3.7,  40.4],
    'Portugal':       [  -9.1,  38.7],
    'Italy':          [  12.5,  41.9],
    'Greece':         [  23.7,  37.9],
    'Switzerland':    [   8.5,  47.4],
    'Austria':        [  16.4,  48.2],
    'Belgium':        [   4.4,  50.8],
    'Chile':          [ -70.7, -33.5],
    'Colombia':       [ -74.1,   4.7],
    'Peru':           [ -77.0, -12.0],
    'Venezuela':      [ -66.9,  10.5],
    'Saudi Arabia':   [  46.7,  24.7],
    'UAE':            [  55.3,  25.2],
    'Morocco':        [  -5.8,  34.0],
    'Algeria':        [   3.1,  36.8],
    'Bangladesh':     [  90.4,  23.7],
    'Sri Lanka':      [  79.9,   6.9],
    'Myanmar':        [  96.2,  16.9],
    'Nepal':          [  85.3,  27.7],
    'Slovakia':       [  17.1,  48.1],
    'Croatia':        [  16.0,  45.8],
    'Azerbaijan':     [  49.9,  40.4],
    'Georgia':        [  44.8,  41.7],
    'Armenia':        [  44.5,  40.2],
    'Uzbekistan':     [  69.3,  41.3],
    // Africa
    'Kenya':          [  36.8,  -1.3],
    'Tanzania':       [  39.3,  -6.8],
    'Ethiopia':       [  38.7,   9.0],
    'Ghana':          [  -0.2,   5.6],
    'Ivory Coast':    [  -4.0,   5.3],
    'Cameroon':       [  11.5,   3.9],
    'Angola':         [  13.2,  -8.8],
    'Mozambique':     [  32.6, -26.0],
    'Zimbabwe':       [  31.0, -17.8],
    'Zambia':         [  28.3, -15.4],
    'Uganda':         [  32.6,   0.3],
    'Rwanda':         [  30.1,  -1.9],
    'Sudan':          [  32.5,  15.6],
    'DR Congo':       [  15.3,  -4.3],
    'Senegal':        [ -17.4,  14.7],
    'Libya':          [  13.2,  32.9],
    'Tunisia':        [  10.2,  36.8],
    'Somalia':        [  45.3,   2.1],
    'Namibia':        [  17.1, -22.6],
    'Botswana':       [  25.9, -24.7],
    'Madagascar':     [  47.5, -18.9],
    'Mali':           [  -8.0,  12.7],
    'Malawi':         [  33.8, -14.0],
    'Burkina Faso':   [  -1.5,  12.4],
    'Niger':          [   2.1,  13.5],
    'Togo':           [   1.2,   6.1],
    'Benin':          [   2.4,   6.4],
    'Guinea':         [ -13.6,   9.5],
    'Mauritius':      [  57.5, -20.2],
    // Middle East
    'Iraq':           [  44.4,  33.3],
    'Syria':          [  36.3,  33.5],
    'Jordan':         [  35.9,  32.0],
    'Kuwait':         [  48.0,  29.4],
    'Qatar':          [  51.5,  25.3],
    'Bahrain':        [  50.6,  26.2],
    'Oman':           [  58.6,  23.6],
    'Lebanon':        [  35.5,  33.9],
    'Yemen':          [  44.2,  15.4],
    'Palestine':      [  35.2,  31.9],
    // Central & South Asia
    'Afghanistan':    [  69.2,  34.5],
    'Kyrgyzstan':     [  74.6,  42.9],
    'Tajikistan':     [  68.8,  38.6],
    'Turkmenistan':   [  58.4,  38.0],
    // East & Southeast Asia
    'Cambodia':       [ 104.9,  11.6],
    'Laos':           [ 102.6,  18.0],
    'Mongolia':       [ 106.9,  47.9],
    // Europe
    'Albania':        [  19.8,  41.3],
    'Bosnia':         [  18.4,  43.9],
    'North Macedonia':[ 21.4,   42.0],
    'Montenegro':     [  19.3,  42.4],
    'Iceland':        [ -22.0,  64.1],
    'Luxembourg':     [   6.1,  49.6],
    'Malta':          [  14.5,  35.9],
    'Cyprus':         [  33.4,  35.2],
    'Ireland':        [  -6.3,  53.3],
    'Slovenia':       [  14.5,  46.1],
    // Americas
    'Bolivia':        [ -68.1, -16.5],
    'Ecuador':        [ -78.5,  -0.2],
    'Paraguay':       [ -57.6, -25.3],
    'Uruguay':        [ -56.2, -34.9],
    'Cuba':           [ -82.4,  23.1],
    'Dominican Republic': [ -69.9, 18.5],
    'Honduras':       [ -87.2,  14.1],
    'Guatemala':      [ -90.5,  14.6],
    'El Salvador':    [ -89.2,  13.7],
    'Costa Rica':     [ -84.1,   9.9],
    'Panama':         [ -79.5,   9.0],
    'Nicaragua':      [ -86.3,  12.1],
    'Guyana':         [ -58.2,   6.8],
    'Trinidad and Tobago': [ -61.5, 10.7],
    'Jamaica':        [ -76.8,  18.0],
    'Haiti':          [ -72.3,  18.5],
    // Oceania
    'New Zealand':    [ 174.8, -41.3],
    'Papua New Guinea': [ 147.2, -9.4],
    'Fiji':           [ 178.4, -18.1],
  },

  FLAGS: {
    'China': '🇨🇳',          'United States': '🇺🇸', 'Russia': '🇷🇺',
    'Brazil': '🇧🇷',         'India': '🇮🇳',          'Germany': '🇩🇪',
    'Netherlands': '🇳🇱',    'France': '🇫🇷',         'United Kingdom': '🇬🇧',
    'South Korea': '🇰🇷',    'Japan': '🇯🇵',           'Ukraine': '🇺🇦',
    'Vietnam': '🇻🇳',         'Iran': '🇮🇷',            'Turkey': '🇹🇷',
    'Indonesia': '🇮🇩',       'Mexico': '🇲🇽',          'Pakistan': '🇵🇰',
    'Nigeria': '🇳🇬',          'South Africa': '🇿🇦',  'Australia': '🇦🇺',
    'Canada': '🇨🇦',           'Argentina': '🇦🇷',      'Egypt': '🇪🇬',
    'Romania': '🇷🇴',          'Bulgaria': '🇧🇬',       'Poland': '🇵🇱',
    'North Korea': '🇰🇵',     'Belarus': '🇧🇾',         'Israel': '🇮🇱',
    'Hong Kong': '🇭🇰',        'Singapore': '🇸🇬',      'Taiwan': '🇹🇼',
    'Thailand': '🇹🇭',         'Malaysia': '🇲🇾',        'Philippines': '🇵🇭',
    'Czech Republic': '🇨🇿',  'Hungary': '🇭🇺',         'Serbia': '🇷🇸',
    'Moldova': '🇲🇩',          'Kazakhstan': '🇰🇿',     'Lithuania': '🇱🇹',
    'Latvia': '🇱🇻',            'Estonia': '🇪🇪',         'Finland': '🇫🇮',
    'Sweden': '🇸🇪',            'Norway': '🇳🇴',          'Denmark': '🇩🇰',
    'Spain': '🇪🇸',              'Portugal': '🇵🇹',        'Italy': '🇮🇹',
    'Greece': '🇬🇷',             'Switzerland': '🇨🇭',    'Austria': '🇦🇹',
    'Belgium': '🇧🇪',            'Chile': '🇨🇱',           'Colombia': '🇨🇴',
    'Peru': '🇵🇪',               'Venezuela': '🇻🇪',       'Saudi Arabia': '🇸🇦',
    'UAE': '🇦🇪',                'Morocco': '🇲🇦',          'Algeria': '🇩🇿',
    'Bangladesh': '🇧🇩',        'Sri Lanka': '🇱🇰',       'Myanmar': '🇲🇲',
    'Nepal': '🇳🇵',              'Slovakia': '🇸🇰',         'Croatia': '🇭🇷',
    'Azerbaijan': '🇦🇿',        'Georgia': '🇬🇪',           'Armenia': '🇦🇲',
    'Uzbekistan': '🇺🇿',
    // Africa
    'Kenya': '🇰🇪',            'Tanzania': '🇹🇿',          'Ethiopia': '🇪🇹',
    'Ghana': '🇬🇭',            'Ivory Coast': '🇨🇮',       'Cameroon': '🇨🇲',
    'Angola': '🇦🇴',           'Mozambique': '🇲🇿',        'Zimbabwe': '🇿🇼',
    'Zambia': '🇿🇲',           'Uganda': '🇺🇬',            'Rwanda': '🇷🇼',
    'Sudan': '🇸🇩',            'DR Congo': '🇨🇩',          'Senegal': '🇸🇳',
    'Libya': '🇱🇾',            'Tunisia': '🇹🇳',           'Somalia': '🇸🇴',
    'Namibia': '🇳🇦',          'Botswana': '🇧🇼',          'Madagascar': '🇲🇬',
    'Mali': '🇲🇱',             'Malawi': '🇲🇼',            'Burkina Faso': '🇧🇫',
    'Niger': '🇳🇪',            'Togo': '🇹🇬',              'Benin': '🇧🇯',
    'Guinea': '🇬🇳',           'Mauritius': '🇲🇺',
    // Middle East
    'Iraq': '🇮🇶',             'Syria': '🇸🇾',             'Jordan': '🇯🇴',
    'Kuwait': '🇰🇼',           'Qatar': '🇶🇦',             'Bahrain': '🇧🇭',
    'Oman': '🇴🇲',             'Lebanon': '🇱🇧',           'Yemen': '🇾🇪',
    'Palestine': '🇵🇸',
    // Central & South Asia
    'Afghanistan': '🇦🇫',     'Kyrgyzstan': '🇰🇬',        'Tajikistan': '🇹🇯',
    'Turkmenistan': '🇹🇲',
    // East & Southeast Asia
    'Cambodia': '🇰🇭',        'Laos': '🇱🇦',              'Mongolia': '🇲🇳',
    // Europe
    'Albania': '🇦🇱',         'Bosnia': '🇧🇦',            'North Macedonia': '🇲🇰',
    'Montenegro': '🇲🇪',      'Iceland': '🇮🇸',           'Luxembourg': '🇱🇺',
    'Malta': '🇲🇹',           'Cyprus': '🇨🇾',            'Ireland': '🇮🇪',
    'Slovenia': '🇸🇮',
    // Americas
    'Bolivia': '🇧🇴',         'Ecuador': '🇪🇨',           'Paraguay': '🇵🇾',
    'Uruguay': '🇺🇾',         'Cuba': '🇨🇺',              'Dominican Republic': '🇩🇴',
    'Honduras': '🇭🇳',        'Guatemala': '🇬🇹',         'El Salvador': '🇸🇻',
    'Costa Rica': '🇨🇷',      'Panama': '🇵🇦',            'Nicaragua': '🇳🇮',
    'Guyana': '🇬🇾',          'Trinidad and Tobago': '🇹🇹', 'Jamaica': '🇯🇲',
    'Haiti': '🇭🇹',
    // Oceania
    'New Zealand': '🇳🇿',     'Papua New Guinea': '🇵🇬',  'Fiji': '🇫🇯',
  },

  THREAT_ACTORS: {
    'Cobalt Strike':   'Various APTs',
    'AsyncRAT':        'Multiple Groups',
    'QakBot':          'TA570',
    'QBot':            'TA570',
    'Emotet':          'TA542',
    'Remcos':          'TA558',
    'NjRAT':           'Various',
    'Agent Tesla':     'Various',
    'RedLine':         'Various',
    'Lumma':           'Various',
    'IcedID':          'TA551',
    'Sliver':          'Various APTs',
    'Havoc':           'Various APTs',
    'Metasploit':      'Various',
    'LockBit':         'LockBit RaaS',
    'BlackCat':        'ALPHV Group',
    'Conti':           'Wizard Spider',
    'REvil':           'Gold Southfield',
    'Hive':            'Hive Group',
    'Black Basta':     'Black Basta',
    'Akira':           'Akira Group',
    'Rhysida':         'Rhysida Group',
    'Play':            'Play Ransomware',
    'Medusa':          'Medusa Group',
    'Mirai':           'IoT Botnet',
    'Moobot':          'Mirai Variant',
    'Stealc':          'Various',
    'Raccoon':         'Various',
    'Vidar':           'Various',
    'FormBook':        'Various',
    'BazarLoader':     'Wizard Spider',
    'SystemBC':        'Various',
    'PikaBot':         'Various',
    'Latrodectus':     'TA577',
  },

};
